# Site settings
name: 张三的博客
email: 42310267@qq.com
author: zhangchengbin
url: https://zhangchengbin.github.io
resume_site: https://zhangchengbin.github.io
github: https://github.com/zhangchengbin/
baseurl: 
description: 生命不止;折腾不休!
meta_description: 生命不止;折腾不休!
motto: We Are Family.
banner: 生命不止;折腾不休!

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zhangchengbin
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light

gems: [jekyll-paginate]